### ISSUE TITLE
Error when connecting to the Switch

### ISSUE THREAD

**Issue by Dada5OOO** [YouTubePlays/JoyConDroid#27]
As soon as I got the to final step of accepting to pair the app with the  Switch I got an error on AMS. How can I solve it?
![IMG_20200419_232811](https://user-images.githubusercontent.com/58867307/79779041-0ed86700-8310-11ea-90f1-f73e5f795ca2.jpg)

**Comment by YouTubePlays** [comment]
Did you try to restart your console?

**Comment by Dada5OOO** [comment]
I've tried it again and didn't had the same error. The problem now is that every time I leave the pairing screen the phone disconnects. Any idea on what I can do to solve it?

**Comment by YouTubePlays** [comment]
yes do the following:
When Switch asks for pairing in Change Order/Grip screen do not accept or reject pairing request. Simply leave Change order/grip screen to upper menu on Switch then accept pairing request. Let me know if this works.

**Comment by Dada5OOO** [comment]
Yes it worked, but now it asked me if I wanted to update the controllers (I chose not to do it) and none of my inputs had answers even tho it was still connected. Btw do I need to have a real controller connect every time I use this app? Thanks for the quick answers I appreciate that.

**Comment by YouTubePlays** [comment]
you can use touch screen and if buttons do not work simply press back and select same ui.

**Comment by Dada5OOO** [comment]
It worked out. Thank you very much.
