### ISSUE TITLE
amiibo file picker to a specific location

### ISSUE THREAD

**Issue by MonsterDruide1** [YouTubePlays/JoyConDroid#28]
As it takes too long to move along the dirs from the /root directory to the folder, where the amiibo-bins are. It would be better to select a folder, which gets saved as the default directory when the amiibo file picker gets opened.

**Comment by uisuke** [comment]
My preference would be to pre select an amiibo through the settings menu, foregoing the selection on the go at all. The Bluetooth connection always disconnects while picking an amiibo. It would be more stable if the card of my choice is pre loaded and remains there until I change it manually again.

**Comment by YouTubePlays** [comment]
Implemented.

**Comment by YouTubePlays** [comment]
1.0.81.3
