### ISSUE TITLE
Restore ad-less version

### ISSUE THREAD

**Issue by MonsterDruide1** [YouTubePlays/JoyConDroid#29]
If you switch to a newer device, Android doesn't remember you have already bought the ad-less version, so it displays ads and offers to buy it again. However, if you try to buy it again, Google remembers you have bought it and so does not allow to buy it again, leading to a failed purchase and still having ads. So I'd suggest adding a "Restore purchases"-button into the settings (a lot of apps have it there), which will check if you already bought ad-free and if yes, restores it.

**Comment by YouTubePlays** [comment]
This should work when you press ad-free on the same account again.
