### ISSUE TITLE
Amiibo doesn't work on 12.0 with 1.0.90.1 on Monster Hunter Rise

### ISSUE THREAD

**Issue by CroqueMr** [YouTubePlays/JoyConDroid#56]
With the new update the controller on the app works perfectly, but when I want to load an amiibo the controller disconects and it's not possible to load an Amiibo

Tested with a Smasung S10, (works perfectly on 11.0 with the previous release)

Edit: Happens only on Monster hunter rise

**Comment by M4th3wIsntHere** [comment]
lower packet rate to 10 in the app settings

**Comment by CroqueMr** [comment]
> lower packet rate to 10 in the app settings

Thanks for the fast reply, I tested the lower the packet rate but unfortunately it does not fix the issue.

**Comment by M4th3wIsntHere** [comment]
switch settings > controllers > disable smth related to USB pro controller communication and try again

**Comment by CroqueMr** [comment]
> switch settings > controllers > disable smth related to USB pro controller communication and try again

It was already disable

**Comment by M4th3wIsntHere** [comment]
are you on the app's latest version? (1.90.0.1)

**Comment by CroqueMr** [comment]
> are you on the app's latest version? (1.0.90.1)

Yes, with the last release it was impossible to connect a controller, with the 1.0.90.1 the controller works perfectly expected the amiibo part.

**Comment by M4th3wIsntHere** [comment]
restart your phone and the switch

**Comment by CroqueMr** [comment]
I tried another game it works well, the issue happens only on Monster Hunter Rise. 
It's very strange

**Comment by M4th3wIsntHere** [comment]
some other ppl were having issues with MHR but the issue was proven not a real issue, as dtrunk (another member of the staff team) tested and it worked fine, i also recieved relates about ppl being able to use amiibo on MHR, so its not a game specific issue

**Comment by CroqueMr** [comment]
I found a fix:
Just load the amiibo directly on the settings, the select screen for the amiibo path induces the disconnection loop

Thank you for your help 👍

**Comment by M4th3wIsntHere** [comment]
you just loaded an amiibo on the intended way, glad it worked
