### ISSUE TITLE
When will it be possible to use rewritable amiibo with joy con droid on Nintendo Switch?

### ISSUE THREAD

**Issue by polltu200** [YouTubePlays/JoyConDroid#60]
It's just that some amiibo require not only reading but also writing information in order to register.  But due to the fact that joy con droid does not support writing, they do not work.

**Comment by M4th3wIsntHere** [comment]
Hello, currently the creator of the app YouTubePlays didn't find a way to write data to amiibos, as JoyConDroid can only send data, not recieve and write it, we're looking forward to amiibo writing but we haven't made any progress, plus this is not been the main focus right now, we can't give an ETA (Estimated Time of Arrival) of when it'll be available.

**Comment by polltu200** [comment]
Ok, I will wait for the joy con droid updates.
